using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Orizon.Distribuidora.Application.Importacoes;
using Orizon.Distribuidora.Application.Interfaces;
using Orizon.Distribuidora.Domain.Enums;
using Orizon.Distribuidora.Infrastructure.Data;
namespace Orizon.Distribuidora.Infrastructure.Services;

public sealed class ExportacaoImportacaoService(ApplicationDbContext db):IExportacaoImportacaoService
{
    public async Task<ArquivoExportacaoImportacao> ExportarExcelAsync(Guid id,Guid company,Guid? user,FiltroExportacaoImportacao filter,CancellationToken ct=default){var data=await Load(id,company,user,filter,ct);return ExportacaoImportacaoRenderer.Excel(data,Name(data,"xlsx",filter));}
    public async Task<ArquivoExportacaoImportacao> ExportarCsvAsync(Guid id,Guid company,Guid? user,FiltroExportacaoImportacao filter,CancellationToken ct=default){var data=await Load(id,company,user,filter,ct);return ExportacaoImportacaoRenderer.Csv(data,Name(data,"csv",filter));}
    private async Task<DadosExportacaoImportacao> Load(Guid id,Guid company,Guid? user,FiltroExportacaoImportacao filter,CancellationToken ct)
    {
        if(user is null||!await db.Users.AsNoTracking().AnyAsync(x=>x.Id==user&&x.CompanyId==company&&x.IsActive,ct))throw new UnauthorizedAccessException("Usuário não autorizado para esta empresa.");
        var h=await db.ImportacoesHistorico.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company,ct)??throw new KeyNotFoundException("Importação não encontrada.");
        var companyName=await db.Companies.AsNoTracking().Where(x=>x.Id==company).Select(x=>x.TradeName).FirstAsync(ct);var userName=await db.Users.AsNoTracking().Where(x=>x.Id==user).Select(x=>x.FullName).FirstAsync(ct);var model=h.ModeloImportacaoId.HasValue?await db.ModelosImportacao.AsNoTracking().Where(x=>x.Id==h.ModeloImportacaoId&&x.CompanyId==company).Select(x=>x.Nome).FirstOrDefaultAsync(ct):null;
        var items=await db.ImportacaoItens.AsNoTracking().Where(x=>x.ImportacaoHistoricoId==id&&x.CompanyId==company).OrderBy(x=>x.NumeroLinha).ToListAsync(ct);var itemIds=items.Select(x=>x.Id).ToList();var errors=await db.ImportacaoErros.AsNoTracking().Where(x=>x.ImportacaoHistoricoId==id&&x.CompanyId==company&&x.ImportacaoItemId!=null&&itemIds.Contains(x.ImportacaoItemId.Value)).ToListAsync(ct);var byItem=errors.GroupBy(x=>x.ImportacaoItemId!.Value).ToDictionary(x=>x.Key,x=>x.ToList());var productIds=items.Where(x=>x.ProdutoId.HasValue).Select(x=>x.ProdutoId!.Value).Distinct().ToList();var persisted=await db.Products.AsNoTracking().Where(x=>x.CompanyId==company&&productIds.Contains(x.Id)).Select(x=>new{x.Id,x.InternalCode,x.Name,x.Barcode,x.ProductType,x.CostPrice,x.SalePrice}).ToDictionaryAsync(x=>x.Id,x=>JsonSerializer.Serialize(x),ct);
        var lines=new List<LinhaExportacaoImportacao>(items.Count);foreach(var item in items){var data=Parse(item.DadosNormalizadosJson);byItem.TryGetValue(item.Id,out var problems);problems??=[];var hasWarning=problems.Any(x=>x.Severidade==SeveridadeValidacao.Aviso);var hasError=problems.Any(x=>x.Severidade==SeveridadeValidacao.Erro)||item.Status==StatusLinhaImportacao.Falhou;var line=new LinhaExportacaoImportacao(item.NumeroLinha,Text(data,"codigo"),Text(data,"descricao"),Text(data,"codigoBarras"),Text(data,"tipoProduto"),item.OperacaoExecucao,item.Status,Join(problems.Select(x=>x.Mensagem).Append(item.MensagemExecucao)),Join(problems.Select(x=>x.Coluna)),Join(problems.Select(x=>x.Codigo)),item.ProdutoId,companyName,userName,item.ExecutadoEm??item.CreatedAt,item.DadosOriginaisJson,item.ProdutoId.HasValue&&persisted.TryGetValue(item.ProdutoId.Value,out var p)?p:item.DadosNormalizadosJson,Join(problems.Where(x=>x.Severidade==SeveridadeValidacao.Aviso).Select(x=>x.Mensagem)),hasWarning,hasError);if(Matches(line,filter))lines.Add(line);}
        return new(new(id,h.NomeArquivo,companyName,userName,h.CreatedAt,h.FinalizadoEm,h.IniciadoEm.HasValue&&h.FinalizadoEm.HasValue?h.FinalizadoEm-h.IniciadoEm:null,h.TotalLinhas,h.ProdutosInseridos,h.ProdutosAtualizados,h.SemAlteracao,h.LinhasIgnoradas,h.ItensBloqueados,h.FalhasExecucao,h.Status,model),lines);
    }
    public static bool Matches(LinhaExportacaoImportacao x,FiltroExportacaoImportacao f)=>f switch{FiltroExportacaoImportacao.Inseridos=>x.Status==StatusLinhaImportacao.Inserida,FiltroExportacaoImportacao.Atualizados=>x.Status==StatusLinhaImportacao.Atualizada,FiltroExportacaoImportacao.SemAlteracao=>x.Status==StatusLinhaImportacao.SemAlteracao,FiltroExportacaoImportacao.Ignorados=>x.Status==StatusLinhaImportacao.Ignorada,FiltroExportacaoImportacao.Bloqueados=>x.Status==StatusLinhaImportacao.Bloqueada,FiltroExportacaoImportacao.Falhas=>x.Status==StatusLinhaImportacao.Falhou,FiltroExportacaoImportacao.Avisos=>x.PossuiAviso,FiltroExportacaoImportacao.Erros=>x.PossuiErro,_=>true};
    private static Dictionary<string,JsonElement> Parse(string? json)=>string.IsNullOrWhiteSpace(json)?[]:JsonSerializer.Deserialize<Dictionary<string,JsonElement>>(json)??[];private static string? Text(Dictionary<string,JsonElement>d,string k)=>d.TryGetValue(k,out var v)?v.ToString():null;private static string? Join(IEnumerable<string?> values){var x=values.Where(v=>!string.IsNullOrWhiteSpace(v)).Distinct().ToList();return x.Count==0?null:string.Join(" | ",x);}
    private static string Name(DadosExportacaoImportacao d,string ext,FiltroExportacaoImportacao f)=>$"importacao-{d.Resumo.ImportacaoId:N}-{f.ToString().ToLowerInvariant()}.{ext}";
}
