using Microsoft.EntityFrameworkCore;
using Orizon.Distribuidora.Application.Importacoes;
using Orizon.Distribuidora.Domain.Entities;
using Orizon.Distribuidora.Domain.Enums;
namespace Orizon.Distribuidora.Infrastructure.Services;

public sealed partial class HistoricoImportacaoService
{
    public async Task<PaginaHistoricoImportacao> ConsultarAsync(Guid companyId,ConsultaHistoricoImportacao c,CancellationToken ct=default)
    {
        var size=HistoricoImportacaoPolicy.NormalizarTamanhoPagina(c.TamanhoPagina);var page=HistoricoImportacaoPolicy.NormalizarPagina(c.Pagina);var q=Filtrar(companyId,c);
        q=(c.OrdenarPor.ToLowerInvariant(),c.Descendente) switch{("usuario",false)=>q.OrderBy(x=>x.UsuarioExecutorId), ("usuario",true)=>q.OrderByDescending(x=>x.UsuarioExecutorId),("arquivo",false)=>q.OrderBy(x=>x.NomeArquivo),("arquivo",true)=>q.OrderByDescending(x=>x.NomeArquivo),("inseridos",false)=>q.OrderBy(x=>x.ProdutosInseridos),("inseridos",true)=>q.OrderByDescending(x=>x.ProdutosInseridos),("falhas",false)=>q.OrderBy(x=>x.FalhasExecucao),("falhas",true)=>q.OrderByDescending(x=>x.FalhasExecucao),("duracao",false)=>q.OrderBy(x=>x.FinalizadoEm-x.IniciadoEm),("duracao",true)=>q.OrderByDescending(x=>x.FinalizadoEm-x.IniciadoEm),(_,false)=>q.OrderBy(x=>x.CreatedAt),_=>q.OrderByDescending(x=>x.CreatedAt)};
        var total=await q.CountAsync(ct);var raw=await q.Skip((page-1)*size).Take(size).Select(x=>new{x.Id,x.NomeArquivo,x.CreatedAt,x.FinalizadoEm,x.IniciadoEm,x.TotalLinhas,x.ProdutosInseridos,x.ProdutosAtualizados,x.SemAlteracao,x.LinhasIgnoradas,x.ItensBloqueados,x.FalhasExecucao,x.LinhasComAviso,x.Status,x.ModeloImportacaoId,UserId=x.UsuarioExecutorId??x.CreatedBy}).ToListAsync(ct);
        var userIds=raw.Where(x=>x.UserId.HasValue).Select(x=>x.UserId!.Value).Distinct().ToList();var users=await dbContext.Users.AsNoTracking().Where(x=>x.CompanyId==companyId&&userIds.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.FullName,ct);var modelIds=raw.Where(x=>x.ModeloImportacaoId.HasValue).Select(x=>x.ModeloImportacaoId!.Value).Distinct().ToList();var models=await dbContext.ModelosImportacao.AsNoTracking().Where(x=>x.CompanyId==companyId&&modelIds.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,x=>x.Nome,ct);var company=await dbContext.Companies.AsNoTracking().Where(x=>x.Id==companyId).Select(x=>x.TradeName).FirstAsync(ct);
        var items=raw.Select(x=>new HistoricoImportacaoLinhaDto(x.Id,x.NomeArquivo,company,x.UserId.HasValue&&users.TryGetValue(x.UserId.Value,out var un)?un:"Sistema",x.CreatedAt,x.FinalizadoEm,x.IniciadoEm.HasValue&&x.FinalizadoEm.HasValue?x.FinalizadoEm-x.IniciadoEm:null,x.TotalLinhas,x.ProdutosInseridos,x.ProdutosAtualizados,x.SemAlteracao,x.LinhasIgnoradas,x.ItensBloqueados,x.FalhasExecucao,x.LinhasComAviso,x.Status,x.ModeloImportacaoId,x.ModeloImportacaoId.HasValue&&models.TryGetValue(x.ModeloImportacaoId.Value,out var mn)?mn:null,null)).ToList();
        var stats=await q.GroupBy(_=>1).Select(g=>new{Count=g.Count(),Imported=g.Sum(x=>x.ProdutosInseridos),Updated=g.Sum(x=>x.ProdutosAtualizados),Failures=g.Sum(x=>x.FalhasExecucao),Last=g.Max(x=>(DateTimeOffset?)x.CreatedAt),Largest=g.Max(x=>(int?)x.TotalLinhas)}).FirstOrDefaultAsync(ct);var durations=await q.Where(x=>x.IniciadoEm.HasValue&&x.FinalizadoEm.HasValue).Select(x=>new{x.IniciadoEm,x.FinalizadoEm}).ToListAsync(ct);var top=await q.Where(x=>x.UsuarioExecutorId.HasValue).GroupBy(x=>x.UsuarioExecutorId!.Value).Select(g=>new{Id=g.Key,Count=g.Count()}).OrderByDescending(x=>x.Count).FirstOrDefaultAsync(ct);var topName=top is null?null:await dbContext.Users.AsNoTracking().Where(x=>x.Id==top.Id&&x.CompanyId==companyId).Select(x=>x.FullName).FirstOrDefaultAsync(ct);var avg=durations.Count==0?TimeSpan.Zero:TimeSpan.FromTicks((long)durations.Average(x=>(x.FinalizadoEm!.Value-x.IniciadoEm!.Value).Ticks));var indicators=new HistoricoIndicadoresDto(stats?.Count??0,stats?.Imported??0,stats?.Updated??0,stats?.Failures??0,avg,stats?.Last,stats?.Largest??0,topName);
        var filterUsers=(await dbContext.Users.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.IsActive).OrderBy(x=>x.FullName).Select(x=>new{x.Id,x.FullName}).ToListAsync(ct)).Select(x=>(x.Id,x.FullName)).ToList();var filterModels=(await dbContext.ModelosImportacao.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.Ativo).OrderBy(x=>x.Nome).Select(x=>new{x.Id,x.Nome}).ToListAsync(ct)).Select(x=>(x.Id,x.Nome)).ToList();return new(items,page,size,total,Math.Max(1,(int)Math.Ceiling(total/(double)size)),indicators,filterUsers,filterModels);
    }
    private IQueryable<ImportacaoHistorico> Filtrar(Guid companyId,ConsultaHistoricoImportacao c){var q=dbContext.ImportacoesHistorico.AsNoTracking().Where(x=>x.CompanyId==companyId);if(c.Inicio.HasValue)q=q.Where(x=>x.CreatedAt>=c.Inicio);if(c.Fim.HasValue)q=q.Where(x=>x.CreatedAt<c.Fim.Value.AddDays(1));if(c.UsuarioId.HasValue)q=q.Where(x=>x.CreatedBy==c.UsuarioId||x.UsuarioExecutorId==c.UsuarioId);if(!string.IsNullOrWhiteSpace(c.Arquivo))q=q.Where(x=>EF.Functions.ILike(x.NomeArquivo,$"%{c.Arquivo.Trim()}%"));if(c.Status.HasValue)q=q.Where(x=>x.Status==c.Status);if(c.ModeloId.HasValue)q=q.Where(x=>x.ModeloImportacaoId==c.ModeloId);if(c.PossuiFalhas.HasValue)q=q.Where(x=>(x.FalhasExecucao>0)==c.PossuiFalhas);if(c.PossuiAvisos.HasValue)q=q.Where(x=>(x.LinhasComAviso>0)==c.PossuiAvisos);if(c.PossuiBloqueios.HasValue)q=q.Where(x=>(x.ItensBloqueados>0)==c.PossuiBloqueios);if(!string.IsNullOrWhiteSpace(c.Pesquisa)){var s=c.Pesquisa.Trim();var ids=dbContext.Users.Where(u=>u.CompanyId==companyId&&EF.Functions.ILike(u.FullName,$"%{s}%")).Select(u=>u.Id);q=q.Where(x=>EF.Functions.ILike(x.NomeArquivo,$"%{s}%")||x.Id.ToString()==s||x.CreatedBy.HasValue&&ids.Contains(x.CreatedBy.Value)||x.UsuarioExecutorId.HasValue&&ids.Contains(x.UsuarioExecutorId.Value));}return q;}
    public async Task<HistoricoImportacaoDetalhesDto?> ObterDetalhesAsync(Guid companyId,Guid id,CancellationToken ct=default){var page=await ConsultarAsync(companyId,new(Pesquisa:id.ToString()),ct);var item=page.Itens.FirstOrDefault(x=>x.Id==id);if(item is null)return null;var p=await dbContext.ImportacaoErros.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.ImportacaoHistoricoId==id).GroupBy(x=>new{x.Codigo,x.Mensagem,x.Severidade}).Select(x=>new{x.Key.Codigo,x.Key.Mensagem,x.Key.Severidade,Count=x.Count()}).OrderByDescending(x=>x.Count).Take(20).ToListAsync(ct);return new(item,p.Where(x=>x.Severidade==SeveridadeValidacao.Erro).Select(x=>$"{x.Codigo} ({x.Count}): {x.Mensagem}").ToList(),p.Where(x=>x.Severidade==SeveridadeValidacao.Aviso).Select(x=>$"{x.Codigo} ({x.Count}): {x.Mensagem}").ToList());}
    public async Task<HistoricoDashboardDto> ObterDashboardAsync(Guid companyId,DateTimeOffset? start=null,DateTimeOffset? end=null,CancellationToken ct=default){var q=dbContext.ImportacoesHistorico.AsNoTracking().Where(x=>x.CompanyId==companyId);if(start.HasValue)q=q.Where(x=>x.CreatedAt>=start);if(end.HasValue)q=q.Where(x=>x.CreatedAt<end.Value.AddDays(1));var data=await q.Select(x=>new{x.CreatedAt,x.IniciadoEm,x.FinalizadoEm,x.ProdutosInseridos}).ToListAsync(ct);var day=data.GroupBy(x=>x.CreatedAt.ToString("yyyy-MM-dd")).OrderBy(x=>x.Key).Select(x=>new PontoDashboardImportacao(x.Key,x.Count())).ToList();var month=data.GroupBy(x=>x.CreatedAt.ToString("yyyy-MM")).OrderBy(x=>x.Key).Select(x=>new PontoDashboardImportacao(x.Key,x.Sum(y=>y.ProdutosInseridos))).ToList();var time=data.Where(x=>x.IniciadoEm.HasValue&&x.FinalizadoEm.HasValue).GroupBy(x=>x.CreatedAt.ToString("yyyy-MM")).OrderBy(x=>x.Key).Select(x=>new PontoDashboardImportacao(x.Key,(decimal)x.Average(y=>(y.FinalizadoEm!.Value-y.IniciadoEm!.Value).TotalSeconds))).ToList();var failures=await dbContext.ImportacaoErros.AsNoTracking().Where(x=>x.CompanyId==companyId&&x.Severidade==SeveridadeValidacao.Erro).GroupBy(x=>x.Codigo).Select(x=>new PontoDashboardImportacao(x.Key,x.Count())).OrderByDescending(x=>x.Valor).Take(10).ToListAsync(ct);return new(day,month,failures,time);}
    public async Task<Guid> DuplicarConfiguracaoAsync(Guid companyId,Guid id,Guid? user,CancellationToken ct=default){var h=await dbContext.ImportacoesHistorico.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==id,ct)??throw new KeyNotFoundException();if(!h.ModeloImportacaoId.HasValue)throw new InvalidOperationException("A importação não possui modelo para duplicar.");var s=await dbContext.ModelosImportacao.AsNoTracking().FirstOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==h.ModeloImportacaoId,ct)??throw new KeyNotFoundException();var copy=new ModeloImportacao(companyId,$"{s.Nome} - Cópia {DateTimeOffset.Now:yyyyMMddHHmmss}",s.TipoArquivo,s.MapeamentoColunasJson,user,s.AssinaturaColunas);copy.CreatedBy=user;dbContext.ModelosImportacao.Add(copy);await dbContext.SaveChangesAsync(ct);return copy.Id;}
    public async Task ExcluirHistoricoAsync(Guid companyId,Guid id,Guid? user,CancellationToken ct=default){var h=await dbContext.ImportacoesHistorico.FirstOrDefaultAsync(x=>x.CompanyId==companyId&&x.Id==id,ct)??throw new KeyNotFoundException();if(!HistoricoImportacaoPolicy.PodeExcluir(h.Status))throw new InvalidOperationException("Não é possível excluir uma importação em processamento.");h.DeletedBy=user;dbContext.ImportacoesHistorico.Remove(h);await dbContext.SaveChangesAsync(ct);}
}
