using System.Globalization;
using System.Text;
using System.Text.Json;
using ClosedXML.Excel;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Orizon.Distribuidora.Application.Importacoes;
using Orizon.Distribuidora.Application.Interfaces;
using Orizon.Distribuidora.Domain.Entities;
using Orizon.Distribuidora.Domain.Enums;
using Orizon.Distribuidora.Infrastructure.Data;
namespace Orizon.Distribuidora.Infrastructure.Services;

public sealed class RollbackImportacaoService(ApplicationDbContext db,ILogger<RollbackImportacaoService> logger):IRollbackImportacaoService
{
    public async Task<AnaliseRollbackImportacao> AnalisarAsync(Guid id,Guid company,Guid? user,CancellationToken ct=default)
    {
        await Authorize(company,user,ct);var h=await db.ImportacoesHistorico.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company,ct)??throw new RollbackImportacaoException("Importação não encontrada.");if(h.Status is StatusImportacao.Revertida or StatusImportacao.RevertidaParcialmente or StatusImportacao.RollbackFalhou or StatusImportacao.RollbackEmAndamento)return new(id,false,0,0,0,TimeSpan.Zero,["A importação já foi revertida ou possui rollback em andamento."]);if(h.Status is not(StatusImportacao.Concluida or StatusImportacao.ConcluidaParcialmente))return new(id,false,0,0,0,TimeSpan.Zero,["Somente importações concluídas permitem rollback."]);
        var items=await db.ImportacaoItens.AsNoTracking().Where(x=>x.CompanyId==company&&x.ImportacaoHistoricoId==id&&x.ProdutoId.HasValue&&(x.Status==StatusLinhaImportacao.Inserida||x.Status==StatusLinhaImportacao.Atualizada)).Select(x=>new{x.ProdutoId,x.Status,x.ExecutadoEm}).ToListAsync(ct);var ids=items.Select(x=>x.ProdutoId!.Value).Distinct().ToList();var origins=$"importação:{id}";var executionEnd=h.FinalizadoEm??h.CreatedAt;var later=await db.ProductChangeHistories.AsNoTracking().Where(x=>x.CompanyId==company&&ids.Contains(x.ProductId)&&x.CreatedAt>executionEnd&&x.Origin!=origins&&x.Origin!=$"rollback:{id}").Select(x=>x.ProductId).Distinct().ToListAsync(ct);var blocked=items.Count(x=>later.Contains(x.ProdutoId!.Value));var risks=new List<string>{"Produtos criados serão removidos logicamente.","Produtos atualizados serão restaurados pelos snapshots de auditoria."};if(blocked>0)risks.Add($"{blocked} produto(s) possuem alterações posteriores e serão bloqueados.");return new(id,items.Count>blocked,items.Count(x=>x.Status==StatusLinhaImportacao.Inserida),items.Count(x=>x.Status==StatusLinhaImportacao.Atualizada),blocked,TimeSpan.FromMilliseconds(items.Count*4),risks);
    }
    public async Task<ResultadoRollbackImportacao> ExecutarAsync(Guid id,Guid company,Guid? user,bool partial,CancellationToken ct=default)
    {
        var analysis=await AnalisarAsync(id,company,user,ct);if(!analysis.Permitido)throw new RollbackImportacaoException(string.Join(" ",analysis.Riscos));if(!partial&&analysis.ProdutosBloqueados>0)throw new RollbackImportacaoException("Existem produtos com uso ou alterações posteriores; rollback integral cancelado.");var start=DateTimeOffset.UtcNow;
        await using var tx=await db.Database.BeginTransactionAsync(ct);try{var h=await db.ImportacoesHistorico.FirstAsync(x=>x.Id==id&&x.CompanyId==company,ct);var executionEnd=h.FinalizadoEm??h.CreatedAt;h.IniciarRollback(user);await db.SaveChangesAsync(ct);var items=await db.ImportacaoItens.Where(x=>x.CompanyId==company&&x.ImportacaoHistoricoId==id&&x.ProdutoId.HasValue&&(x.Status==StatusLinhaImportacao.Inserida||x.Status==StatusLinhaImportacao.Atualizada)).OrderBy(x=>x.NumeroLinha).ToListAsync(ct);var ids=items.Select(x=>x.ProdutoId!.Value).Distinct().ToList();var products=await db.Products.IgnoreQueryFilters().Where(x=>x.CompanyId==company&&ids.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct);var origin=$"importação:{id}";var later=(await db.ProductChangeHistories.AsNoTracking().Where(x=>x.CompanyId==company&&ids.Contains(x.ProductId)&&x.CreatedAt>executionEnd&&x.Origin!=origin&&x.Origin!=$"rollback:{id}").Select(x=>x.ProductId).Distinct().ToListAsync(ct)).ToHashSet();var removed=0;var restored=0;var blocked=0;var failures=0;var results=new List<ResultadoRollbackItem>();
        foreach(var item in items){ct.ThrowIfCancellationRequested();var pid=item.ProdutoId!.Value;if(later.Contains(pid)){item.RegistrarRollback(false,"Bloqueado por alterações posteriores.");blocked++;results.Add(new(item.NumeroLinha,pid,"Bloquear",false,item.MensagemRollback!));continue;}if(!products.TryGetValue(pid,out var p)){item.RegistrarRollback(false,"Produto não encontrado.");failures++;results.Add(new(item.NumeroLinha,pid,"Falha",false,item.MensagemRollback!));if(!partial)throw new RollbackImportacaoException(item.MensagemRollback!);continue;}try{if(item.Status==StatusLinhaImportacao.Inserida){p.DeletedBy=user;db.Products.Remove(p);removed++;item.RegistrarRollback(true,"Produto removido logicamente.");db.ProductChangeHistories.Add(new(company,p.Id,"Produto","Ativo","Excluído",$"rollback:{id}"){CreatedBy=user});results.Add(new(item.NumeroLinha,pid,"Remover",true,item.MensagemRollback!));}else{Restore(p,item.AlteracoesAplicadasJson);p.UpdatedBy=user;restored++;item.RegistrarRollback(true,"Valores anteriores restaurados.");db.ProductChangeHistories.Add(new(company,p.Id,"Produto","Importado","Restaurado",$"rollback:{id}"){CreatedBy=user});results.Add(new(item.NumeroLinha,pid,"Restaurar",true,item.MensagemRollback!));}}catch(Exception ex) when(ex is ArgumentException or InvalidOperationException or JsonException){logger.LogWarning(ex,"Rollback bloqueado para produto {Product}",pid);item.RegistrarRollback(false,ex.Message);failures++;results.Add(new(item.NumeroLinha,pid,"Falha",false,ex.Message));if(!partial)throw;}}
        h.FinalizarRollback(removed,restored,blocked,failures,$"Rollback {(partial?"parcial":"integral")} executado.");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);return new(id,removed,restored,blocked,failures,start,h.RollbackFinalizadoEm!.Value,h.Status,[],results);}catch(Exception ex){await tx.RollbackAsync(ct);logger.LogError(ex,"Falha no rollback {ImportId}",id);db.ChangeTracker.Clear();var h=await db.ImportacoesHistorico.FirstOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company,ct);if(h is not null&&h.Status==StatusImportacao.RollbackEmAndamento){h.FinalizarRollback(0,0,0,1,"Rollback revertido por falha transacional.");await db.SaveChangesAsync(ct);}throw new RollbackImportacaoException("Não foi possível concluir o rollback com segurança.");}
    }
    public async Task<ResultadoRollbackImportacao?> ObterResultadoAsync(Guid id,Guid company,CancellationToken ct=default){var h=await db.ImportacoesHistorico.AsNoTracking().FirstOrDefaultAsync(x=>x.Id==id&&x.CompanyId==company,ct);if(h is null||h.RollbackFinalizadoEm is null)return null;var items=await db.ImportacaoItens.AsNoTracking().Where(x=>x.CompanyId==company&&x.ImportacaoHistoricoId==id&&x.RollbackExecutadoEm.HasValue).OrderBy(x=>x.NumeroLinha).Select(x=>new ResultadoRollbackItem(x.NumeroLinha,x.ProdutoId,x.Status==StatusLinhaImportacao.Inserida?"Remover":"Restaurar",x.Revertido,x.MensagemRollback??"")).ToListAsync(ct);return new(id,h.ProdutosRemovidosRollback,h.ProdutosRestauradosRollback,h.ProdutosBloqueadosRollback,h.FalhasRollback,h.RollbackIniciadoEm??h.CreatedAt,h.RollbackFinalizadoEm.Value,h.Status,string.IsNullOrWhiteSpace(h.ObservacoesRollback)?[]:[h.ObservacoesRollback],items);}
    public async Task<ArquivoExportacaoImportacao> ExportarExcelAsync(Guid id,Guid company,CancellationToken ct=default){var r=await ObterResultadoAsync(id,company,ct)??throw new KeyNotFoundException();using var wb=new XLWorkbook();var ws=wb.AddWorksheet("Rollback");var headers=new[]{"Linha","Produto","Operação","Revertido","Mensagem"};for(var c=0;c<headers.Length;c++){ws.Cell(1,c+1).Value=headers[c];ws.Cell(1,c+1).Style.Font.Bold=true;}for(var n=0;n<r.Itens.Count;n++){var i=r.Itens[n];ws.Cell(n+2,1).Value=i.Linha;ws.Cell(n+2,2).Value=i.ProdutoId?.ToString()??"";ws.Cell(n+2,3).Value=i.Operacao;ws.Cell(n+2,4).Value=i.Revertido?"Sim":"Não";ws.Cell(n+2,5).Value=i.Mensagem;}ws.SheetView.FreezeRows(1);ws.RangeUsed()?.SetAutoFilter();ws.Columns().AdjustToContents();using var ms=new MemoryStream();wb.SaveAs(ms);return new(ms.ToArray(),$"rollback-{id:N}.xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");}
    public async Task<ArquivoExportacaoImportacao> ExportarCsvAsync(Guid id,Guid company,CancellationToken ct=default){var r=await ObterResultadoAsync(id,company,ct)??throw new KeyNotFoundException();using var ms=new MemoryStream();using(var w=new StreamWriter(ms,new UTF8Encoding(true),leaveOpen:true)){w.WriteLine("Linha;Produto;Operação;Revertido;Mensagem");foreach(var i in r.Itens)w.WriteLine($"{i.Linha};{i.ProdutoId};{Csv(i.Operacao)};{(i.Revertido?"Sim":"Não")};{Csv(i.Mensagem)}");}return new(ms.ToArray(),$"rollback-{id:N}.csv","text/csv; charset=utf-8");}
    private async Task Authorize(Guid company,Guid? user,CancellationToken ct){if(user is null||!await db.Users.AsNoTracking().AnyAsync(x=>x.Id==user&&x.CompanyId==company&&x.IsActive,ct)){logger.LogWarning("Tentativa de rollback não autorizada. Empresa {CompanyId}, usuário {UserId}",company,user);throw new UnauthorizedAccessException();}}
    private static string Csv(string s)=>"\""+s.Replace("\"","\"\"").Replace("\r"," ").Replace("\n"," ")+"\"";
    private static void Restore(Product p,string? json){if(string.IsNullOrWhiteSpace(json))throw new RollbackImportacaoException("Snapshot de alterações indisponível.");var changes=JsonSerializer.Deserialize<Dictionary<string,RollbackChange>>(json)??throw new JsonException();string? Old(string key,string? fallback)=>changes.TryGetValue(key,out var x)?x.ValueString():fallback;var unit=Guid.TryParse(Old("Unidade",p.UnitOfMeasureId.ToString()),out var u)?u:p.UnitOfMeasureId;var type=Enum.TryParse<ProductType>(Old("Tipo",p.ProductType.ToString()),out var t)?t:p.ProductType;var cost=ParseDecimal(Old("Preço de custo",p.CostPrice.ToString()),p.CostPrice);var sale=ParseDecimal(Old("Preço de venda",p.SalePrice.ToString()),p.SalePrice);p.Update(p.InternalCode,p.Sku,Old("Código de barras",p.Barcode),p.Reference,Old("Descrição",p.Name)!,p.ShortDescription,p.Description,type,p.ControlsStock,p.IsActive,p.CategoryId,p.SubcategoryId,p.BrandId,unit,p.ProductGroupId,p.MainSupplierId,p.PartnerId,p.DefaultWarehouseId,p.DefaultWarehouseLocationId,p.Ncm,p.Cest,cost,sale,p.CommissionType,p.CommissionValue,p.PriceValidUntil,p.MinimumStock,p.Notes);}
    private static decimal ParseDecimal(string? value,decimal fallback)=>decimal.TryParse(value,NumberStyles.Any,CultureInfo.CurrentCulture,out var x)||decimal.TryParse(value,NumberStyles.Any,CultureInfo.InvariantCulture,out x)?x:fallback;
    private sealed record RollbackChange(JsonElement Value,JsonElement Novo){public string? ValueString()=>Value.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined?null:Value.ToString();}
}
